# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../config-infra-dev.yml

trigger:
- none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlopsv2-templates 
      name: tgokal/mlopsv2-templates 
      endpoint: github-connection
      type: github
      ref: main #branch name

stages :
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
    - job: CreateStorageForTerraform
      displayName: Create Storage for Terraform
      steps:
      - checkout: self
        path: s/
      - checkout: mlopsv2-templates
        path: s/templates/
      - template: templates/infra/create-resource-group.yml@mlopsv2-templates
      - template: templates/infra/create-storage-account.yml@mlopsv2-templates
      - template: templates/infra/create-storage-container.yml@mlopsv2-templates
  - stage: DeployAzureMachineLearningRG
    displayName: Deploy AML Workspace
    jobs:
    - job:  DeployAMLWorkspace
      displayName: Deploy Terraform
      steps:
      - checkout: self
        path: s/
      - checkout: mlopsv2-templates
        path: s/templates/
      - template: templates/infra/create-sp-variables.yml@mlopsv2-templates
      - template: templates/infra/install-terraform.yml@mlopsv2-templates
      - template: templates/infra/run-terraform-init.yml@mlopsv2-templates
      - template: templates/infra/run-terraform-validate.yml@mlopsv2-templates
      - template: templates/infra/run-terraform-plan.yml@mlopsv2-templates
      - template: templates/infra/run-terraform-apply.yml@mlopsv2-templates
